[package]
name = "rust"
version = "0.3.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
clap = {version= "4.5.23", features = ["derive"]}
indicatif = "0.17.9"
rand = "0"
rayon = "1.10.0"

[profile.dev]
opt-level = 3
